name: Release

on:
  push:
   branches:
     - main
   tags-ignore: 
      - '*'
  workflow_dispatch:

jobs:
  
  bump:
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      # Starting from a fresh checkout to have the git history
      - uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: npm i
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: npx semantic-release